version: '3.8'
networks:
  backend-servers:
    external: 
      name: backend-servers
volumes:
  db:
    driver: local
services:
  mongo:
    image: mongo:4.4.2
    restart: always
    container_name: mongo_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: zOOmed
      MONGO_INITDB_DATABASE: zoomed
    volumes:
      - db:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - backend-servers

  zoomed_back:
    container_name: zoomed_back
    build: .
    env_file:
      - ./.env
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend-servers
    command: >
      bash -c "yarn install
      && npx migrate-mongo up && yarn start:dev"